version: "3"
services:
  react_native:
    container_name: react_native
    build: ./docker_react_native
    volumes:
      - ./react_native/:/usr/src/app
    tty: true
    stdin_open: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    env_file: .env
    # command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

